from datetime import datetime 
import pymysql
# count = 0 

db = pymysql.connect( host = 'localhost',
      passwd = 'test', user = 'test', db='watershe_seabright')
print("connected")
cursor = db.cursor()

def saveData(Temp1, Temp2, RPM1, RPM2, Depth1, Depth2, A1, A2, KWH1, KWH2, V1, V2):
	now = datetime.now()
 	time = str(now.hour) + ":" + str(now.minute) 
 	date = str(now.year) + "-" + str(now.month) + "-" + str(now.day)
 	insert_string = """INSERT INTO seabright_data (Date, Time, `Temp 1`, `Temp 2`, `RPM 1`, `RPM 2`, `Depth 1`, `Depth 2`, A1, A2, `KWH 1`, `KWH 2`, V1, V2) VALUES ('%s', '%s', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""" % (date,time,Temp1, Temp2, RPM1, RPM2, Depth1, Depth2, A1, A2, KWH1, KWH2, V1, V2)
	print insert_string
	try:
	    cursor.execute(insert_string)
	    db.commit()
 	    print "added to data base"
 	except:     
 		db.rollback()
 		print "exception occured" 
 		
